### ISSUE TITLE
Add support for multiple content sets

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/poorly-named-resume-generator#7]
### User Story

As a candidate, I'd like to be able to tailor the contents of my resume to the potential employees I'm sending it to.  I also want to [avoid having to rewrite](https://en.wikipedia.org/wiki/Don't_repeat_yourself) the same contents for each employer.
### Proposal

So here's what I'm thinking.
#### Input

YAML supports [references](http://yaml.org/YAML_for_ruby.html#simple_alias_example)!  In the [YAML spec](http://www.yaml.org/spec/1.1/#id863390), a node is marked as an anchor, while another node aliases that anchor.

Assume that Bojack Horseman is again looking for work, and for some reason needs to send his resume out.  He puts his full employment history (reduced here for clarity) into a full_history.yaml file, like so:

``` yaml

---
author:
    name: Bojack Horseman
    location: Hollywoo, CA
    phone: +1(555)-123-1234

positions:
    - &standup
        company: Various
        location: Greater Hollywood Area
        start: The 80s
        end: 1987
        title: Stand-up Comedian
    - &horsin_around
        company: Nickelodeon
        location: Hollywood, CA
        start: 1987
        end: 1996
        title: Male Lead
        team: Horsin Around'
    - &hsaswdtkdtktlfo
        company: NBC
        location: Hollywoo, CA
        start: 2015
        end: 2015
        title: Guest Star
        team: Hollywoo Stars and Celebrities: What Do They Know? Do They Know Things?? Let's Find Out!
    - &secretariat
        company: (Unknown)
        location: Hollywoo, CA
        start: 2014
        end: 2015
        title: Male Lead
        team: Secretariat
```

If he's looking for any job he can get his hands (hooves?) on, he'll likely be very inclusive with his resume.  He might send a resume to Princess Carolyn at Vigor Entertainment with the following contents:

``` yaml
resumes:
    # (...)
    - vigor:
        author: *author
        positions:
            - *standup
            - *horsin_around
            - *hsaswdtkdtktlfo
            - *secretariat
```

If he wants to have the well-connected Vanessa Gekko try to find him a job at the same time, he may send her a more selective resume.  He wasn't very popular in his standup days, and that one episode of _HSAC!WDTK?DTKT??LFO!_ wasn't very good for his reputation, so he leaves those out.  He'll still take credit for _Horsin' Around_ and _Secretariat_, as they showcase the full range of his acting abilities.

``` yaml
resumes:
    # (...)
    - princess_carolyn:
        author: *author
        positions:
            - *standup
            - *horsin_around
            - *hsaswdtkdtktlfo
            - *secretariat
    - vanessa_gekko:
         author: *author
         positions: 
             - *horsin_around
             - *secretariat
```
#### Output

After running the resume generator, Bojack should see two parallel trees in the `output/` directory, each containing all requested output formats:

```
$ tree output
output
├── princess_carolyn
│   ├── horseman_resume_formatted.txt
│   ├── horseman_resume.pdf
│   ├── horseman_resume.tex
│   └── horseman_resume.txt
└── vanessa_gekko
    ├── horseman_resume_formatted.txt
    ├── horseman_resume.pdf
    ├── horseman_resume.tex
    └── horseman_resume.txt
```
#### Interface

To make rapid iteration possible, the generator must be configurable to generate only certain output datasets.  In practice, generating only Princess Carolyn's output might look something like:

``` shell
$ python generate_resume.py --output-name horseman_resume --generate-only princess_carolyn full_history.yaml
```

The default (i.e. no `--generate-only` arguments) should be to generate all outputs, however.  How that's determined still needs a little bit of thought, but if all outputs are configured in a YAML sequence it would be pretty easy to iterate over the sequence.
